### ISSUE TITLE
Twitter frame doesn't seem to be resizing

### ISSUE THREAD

**Issue by FreeTrade** [jcs/twitframe#1]
Thanks for this. Been using twitframe on memberapp.github.io/

Ran into this when trying to resize the frame to fit the tweet -

Examples at bottom of main site seem similarly affected 
https://twitframe.com/?ref=t

**Comment by jcs** [comment]
Can you see if it works better for you now?

**Comment by FreeTrade** [comment]
Yes thanks! I'll try applying the new code to my own project.

**Comment by FreeTrade** [comment]
Thanks! It's working when loading from my website -
https://freetrade.github.io/memberdev/?b87f#thread?post=b87ffbf9f1

It's erroring when I'm loading from my filesystem -
SyntaxError: An invalid or illegal string was specified show:133
    sendResponse https://twitframe.com/show?url=https://twitter.com/btcfork/status/1207097286028865542:133
    checkHeight https://twitframe.com/show?url=https://twitter.com/btcfork/status/1207097286028865542:119


Maybe related to -
https://stackoverflow.com/questions/18925417/syntax-error-for-cross-domain-messaging

**Comment by FreeTrade** [comment]
nb, I'm not using jquery, so had to rework the code a little - feel free to use -

`/* listen for the return message once the tweet has been loaded */

function listenForTwitFrameResizes() {
  /* find all iframes with ids starting with "tweet_" */
  var tweetIframes=document.querySelectorAll("*[id^='tweet_']");
  tweetIframes.forEach(element => {
    element.onload=function() {
      this.contentWindow.postMessage({ element: this.id, query: "height" },
          "https://twitframe.com");
    };
  });
  
}

/* listen for the return message once the tweet has been loaded */
window.onmessage = (oe) => {
  if (oe.origin != "https://twitframe.com")
      return;
  if (oe.data.height && oe.data.element.match(/^tweet_/))
      document.getElementById(oe.data.element).style.height = parseInt(oe.data.height) + "px"; 
}`
